### ISSUE TITLE
/etc/fstab entry for mediafire-fuse

### ISSUE THREAD

**Issue by centminmod** [MediaFire/mediafire-fuse#19]
Hi what's the correct way/syntax for mounting mediafire-fuse in /etc/fstab which points to a specific config file for username/password ?

i have for cli command line the following

    mediafire-fuse -o uid=500 -o gid=500 -o allow_root -o big_writes -o fsname=mediafire -o subtype=ext4 --config /root/.config/mediafire-tools/config /mfshare

**Comment by josch** [comment]
This would require that the mediafire fuse module will first try to parse a system-wide configuration file, probably in `/etc/mediafire-tools/`, before trying the user specific one.

**Comment by josch** [comment]
Additionally, the `mount` command is a setuid program. This means that the mediafire-fuse binary will be executed as root user no matter as what user you executed `mount`. This in turn means that the mediafire fuse module must be able to create a cache and config in other directories than the home directory of root.

**Comment by josch** [comment]
A workaround would be to put the following in your `/etc/fstab`:

    /usr/bin/mediafire-fuse /mountpoint fuse user,noauto 0 0

The `noauto` option is necessary because this will fail otherwise when auto mounting on boot. The `user` option allows you to run `mount` as non-root. You can then mount using the following command:

    XDG_CONFIG_HOME=/home/username/.config XDG_CACHE_HOME=/home/username/.cache mount /mountpoint

Setting these two environment variables will ensure that `mediafire-fuse` will use the right directories for the config and cache.

It might be possible to remidy this by moving the code which initializes the cache into the fuse initialization routines which are executed with dropped priviliges.

**Comment by centminmod** [comment]
thanks @josch for the info :)

**Comment by TragicWarrior** [comment]
@josch , can you reformat these instructions into the README.md and then we can close out this ticket.

**Comment by josch** [comment]
done
